ALTER TABLE `corporate_gift_request`
  ADD COLUMN IF NOT EXISTS `status` VARCHAR(191) NOT NULL DEFAULT 'Pending',
  ADD COLUMN IF NOT EXISTS `handledByPidUser` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `handledByEmail` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `handledByName` VARCHAR(191) NULL;
