'use client';
import { useEffect, useRef, useState } from 'react';
import { RefreshCw, Wallet } from 'lucide-react';
import type { ButtonHTMLAttributes } from 'react';
function Button({variant, className='', ...props}: ButtonHTMLAttributes<HTMLButtonElement> & {variant?: 'outline'}) {return <button type="button" className={`inline-flex min-h-11 items-center justify-center rounded-lg border px-4 py-2 text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 ${variant==='outline'?'border-border bg-card text-foreground hover:bg-muted':'border-primary bg-primary text-primary-foreground hover:opacity-90'} ${className}`} {...props}/>;}
type Data={balances:Record<string,string>;bank:{bankName:string;accountName:string;accountNumberMasked:string}|null;credits:{orderId:string;amountMinor:string;state:string;deliveryConfirmedAt:string|null}[];withdrawals:{id:string;amountMinor:string;status:string;failureCode:string|null;bank?:{bankName:string;accountNumberMasked:string;accountName:string}}[]};
const money=(v:string)=>{const n=BigInt(v);return `₦${(n/BigInt(100)).toLocaleString('en-NG')}.${(n%BigInt(100)).toString().padStart(2,'0')}`;};
const field='min-h-11 w-full rounded-lg border border-border bg-background px-3 py-2 text-base text-foreground';
export default function WalletReview(){
 const requestSerial=useRef(0);
 const [businesses,setBusinesses]=useState<{id:string;legalName:string}[]>([]),[search,setSearch]=useState(''),[partnerId,setPartnerId]=useState(''),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [review,setReview]=useState<{id:string;action:string}|null>(null),[evidence,setEvidence]=useState(''),[otp,setOtp]=useState(''),[confirmed,setConfirmed]=useState(false);
 async function read(id=partnerId){const serial=++requestSerial.current;setLoading(true);setError('');try{const r=await fetch('/api/partners/wallet'+(id?'?partnerId='+encodeURIComponent(id):''),{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.message);if(serial!==requestSerial.current)return;if(id)setData(d);else setBusinesses(d.businesses);}catch(e){setError(e instanceof Error?e.message:'Unable to load wallets.');}finally{if(serial===requestSerial.current)setLoading(false);}}
 useEffect(()=>{void read('');},[]);
 useEffect(()=>{setData(null);setReview(null);if(partnerId)void read(partnerId);},[partnerId]);
 function open(id:string,action:string){setReview({id,action});setEvidence('');setOtp('');setConfirmed(false);setNotice('');}
 async function act(){if(!review||!confirmed||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/partners/wallet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...review,evidence,otp,confirmed})});const d=await r.json();if(!r.ok)throw new Error(d.message);setNotice(d.message);setReview(null);await read();}catch(e){setError(e instanceof Error?e.message:'Operation requires reconciliation.');}finally{setBusy(false);}}
 return <div className="space-y-6 text-foreground">
  <div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight">Partner wallets</h1><p className="mt-1 text-sm text-muted-foreground">Review customer-released earnings and process verified bank withdrawals.</p></div><Button variant="outline" disabled={loading||busy} onClick={()=>read()}><RefreshCw size={16} className={loading?'mr-2 animate-spin':'mr-2'}/>{loading?'Refreshing…':'Refresh'}</Button></div>
  {error&&<p className="rounded-xl border border-destructive p-4 text-sm" role="alert">{error}</p>}{notice&&<p className="rounded-xl border border-border bg-muted p-4 text-sm" role="status">{notice}</p>}
  <section className="grid gap-4 rounded-xl border border-border bg-card p-5 sm:grid-cols-2"><label className="space-y-2 text-sm font-medium"><span>Find business</span><input className={field} type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search business name"/></label><label className="space-y-2 text-sm font-medium"><span>Business wallet</span><select className={field} value={partnerId} onChange={e=>setPartnerId(e.target.value)} disabled={busy}><option value="">Select business</option>{businesses.filter(b=>b.id===partnerId||b.legalName.toLowerCase().includes(search.toLowerCase())).map(b=><option value={b.id} key={b.id}>{b.legalName}</option>)}</select></label></section>
  {!data?<section className="flex min-h-64 flex-col items-center justify-center gap-3 rounded-xl border border-dashed border-border bg-card px-6 text-center"><Wallet className="h-8 w-8 text-muted-foreground"/><h2 className="text-lg font-semibold">{loading?'Loading wallet…':businesses.length?'Select a business wallet':'No partner wallets yet'}</h2><p className="max-w-md text-sm text-muted-foreground">Wallets appear when a business sets up its bank account or receives its first eligible payment.</p></section>:<>
   <div className="grid grid-cols-2 gap-4 lg:grid-cols-3">{Object.entries(data.balances).map(([key,value])=><section key={key} className="rounded-xl border border-border bg-card p-5"><p className="text-sm capitalize text-muted-foreground">{key==='adjustmentDue'?'Adjustment due':key==='reserved'?'Withdrawal reservations':key}</p><strong className="mt-2 block break-words text-2xl font-semibold">{money(value)}</strong></section>)}</div>
   <section className="rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Verified withdrawal destination</h2><p className="mt-2 text-sm text-muted-foreground">{data.bank?`${data.bank.bankName} · ${data.bank.accountNumberMasked} · ${data.bank.accountName}`:'The business has not set up a withdrawal bank account.'}</p><p className="mt-2 text-sm text-muted-foreground">Each request retains its bank destination at the time of submission. Fund the Sure Imports Paystack balance before sending. Never send a second manual transfer for an uncertain request.</p></section>
   {review&&<section className="space-y-4 rounded-xl border border-border bg-card p-5" aria-labelledby="wallet-review-title"><h2 id="wallet-review-title" className="text-lg font-semibold">Confirm {review.action.toLowerCase()}</h2><p className="break-all text-sm text-muted-foreground">{review.id}</p>{review.action==='EXECUTE'?<><p className="text-sm">This authorizes a real bank transfer from the funded Paystack balance. A retry reuses this same payment reference.</p><label className="block space-y-2 text-sm">Paystack OTP (only if required)<input className={field} inputMode="numeric" autoComplete="one-time-code" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,10))}/></label></>:review.action==='RECONCILE'?<p className="text-sm">Check the current provider outcome without initiating another transfer.</p>:<label className="block space-y-2 text-sm">Review evidence and reason (at least 20 characters)<textarea className={field} rows={4} value={evidence} maxLength={2000} onChange={e=>setEvidence(e.target.value)}/><span className="text-muted-foreground">Confirm the dispute is resolved before releasing a hold. Earnings return to Pending unless the customer has confirmed receipt. Fulfilment holds require a separate order review.</span></label>}<label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1 h-4 w-4" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I have reviewed this request and authorize this action.</label><div className="flex flex-wrap gap-3"><Button disabled={busy||!confirmed||(!['EXECUTE','RECONCILE'].includes(review.action)&&evidence.trim().length<20)} onClick={act}>{busy?'Processing…':'Confirm action'}</Button><Button variant="outline" disabled={busy} onClick={()=>setReview(null)}>Cancel</Button></div></section>}
   <section className="rounded-xl border border-border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">Withdrawal requests</h2>{!data.withdrawals.length?<p className="py-8 text-center text-sm text-muted-foreground">No withdrawal requests for this business.</p>:data.withdrawals.map(w=><article key={w.id} className="flex flex-wrap items-center gap-4 border-t border-border py-5"><div className="min-w-48 flex-1"><strong>{money(w.amountMinor)}</strong><p className="mt-1 break-all text-sm text-muted-foreground">{w.id}</p>{w.bank&&<p className="mt-1 text-sm text-muted-foreground">{w.bank.bankName} · {w.bank.accountNumberMasked} · {w.bank.accountName}</p>}<p className="mt-1 text-sm">{w.status.replaceAll('_',' ')}{w.failureCode?' · Provider outcome uncertain':''}</p></div><div className="flex flex-wrap gap-2">{(w.status==='REQUESTED'||w.status==='OTP_REQUIRED'||w.failureCode==='PROVIDER_UNCERTAIN')&&<Button disabled={busy} onClick={()=>open(w.id,'EXECUTE')}>{w.status==='OTP_REQUIRED'?'Authorize with OTP':w.status==='REQUESTED'?'Send withdrawal':'Retry same reference'}</Button>}{!['REQUESTED','CANCELLED'].includes(w.status)&&<Button variant="outline" disabled={busy} onClick={()=>open(w.id,'RECONCILE')}>Reconcile</Button>}</div></article>)}</section>
   <section className="rounded-xl border border-border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">Order earnings</h2>{!data.credits.length?<p className="py-8 text-center text-sm text-muted-foreground">No earnings recorded for this business.</p>:data.credits.map(c=><article key={c.orderId} className="flex flex-wrap items-center gap-4 border-t border-border py-5"><div className="min-w-48 flex-1"><strong>{money(c.amountMinor)}</strong><p className="mt-1 break-all text-sm text-muted-foreground">Order {c.orderId}</p><p className="mt-1 text-sm">{c.state} · {c.deliveryConfirmedAt?'Customer receipt confirmed':'Awaiting customer receipt'}</p></div>{c.state!=='REVERSED'&&<div className="flex flex-wrap gap-2">{c.state!=='HELD'&&<Button variant="outline" onClick={()=>open(c.orderId,'HOLD')}>Hold</Button>}{c.state==='HELD'&&<Button variant="outline" onClick={()=>open(c.orderId,'RELEASE')}>Release hold</Button>}<Button variant="outline" onClick={()=>open(c.orderId,'REVERSE')}>Reverse earning</Button></div>}</article>)}</section>
  </>}
 </div>;
}
