import test from 'node:test';
import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
const f={queries:[],writes:[]};globalThis.__approvalFlow=f;
const encode=v=>Buffer.from(JSON.stringify(v)).toString('base64');
const reset=()=>{f.row={revision:2,status:'SUBMITTED',businessStatus:'PENDING',kycStatus:'VERIFIED',country:'NG',currency:'NGN',ownerPidUser:'owner',detailsCiphertext:encode({businessReadiness:{responsibilitiesAccepted:true}}),reviewCiphertext:encode({businessFit:{decision:'PILOT_APPROVED',hardBlockersCleared:true}})};f.writes=[];f.agreementReady=true;f.affiliate=false;f.conflict=false;};
f.db={$transaction:async fn=>fn({$queryRaw:async(strings,...values)=>{const sql=strings.join('?');f.queries.push(sql);assert.match(sql,/FOR UPDATE/);if(sql.includes('FROM users'))return[{userEmail:'synthetic@example.invalid'}];if(sql.includes('FROM commercial_program_memberships'))return[{program:f.conflict?'AFFILIATE':'PARTNER',subjectId:f.conflict?'affiliate:1':'partner:fixture'}];if(sql.includes('FROM affiliate_accounts'))return f.affiliate?[{id:1}]:[];return [f.row];},$executeRaw:async(strings,...values)=>{f.writes.push({sql:strings.join('?'),values});return 1;}})};
const hook=registerHooks({resolve(s,c,n){const inline=code=>({url:'data:text/javascript,'+encodeURIComponent(code),shortCircuit:true});if(s==='./agreement')return inline('export const adminAgreement=async()=>({status:globalThis.__approvalFlow.agreementReady?"AWAITING_CONFIRMATION":"AWAITING_ACCEPTANCE",receipt:{reference:"AGR-12345678-1234-1234-1234-123456789abc"}})');if(s==='server-only')return inline('export {};');if(s==='@/lib/prisma')return inline('export const prisma=globalThis.__approvalFlow.db');if(s==='./kyc-crypto')return inline('export const encryptKyc=b=>b;export const decryptKyc=b=>b');if(s==='./review')return inline('export class ReviewError extends Error{constructor(message,status=400){super(message);this.status=status}}');if(['./activation-policy','./business-fit-policy'].includes(s))return n(s+'.ts',c);return n(s,c)}});
const {activatePartner}=await import('../lib/partners/activation.ts');
const {decideBusinessFit}=await import('../lib/partners/business-fit.ts');hook.deregister();
const previousKey=process.env.AFFILIATE_SECURITY_KEY;process.env.AFFILIATE_SECURITY_KEY=Buffer.alloc(32,1).toString('base64');test.after(()=>{if(previousKey===undefined)delete process.env.AFFILIATE_SECURITY_KEY;else process.env.AFFILIATE_SECURITY_KEY=previousKey});
const agreement={revision:2,agreementReference:'AGR-12345678-1234-1234-1234-123456789abc',agreementReviewed:true};
const input={revision:2,decision:'PILOT_APPROVED',scores:{audience:5,acquisition:5,operations:5,demand:5,understanding:5},evidence:'Specific evidence reviewed by a human reviewer.',concerns:'No unresolved concerns.',message:'Your business plan is suitable for a pilot.',hardBlockersCleared:true,overrideReason:'',pilotDays:45,pilotTargets:'Review enquiries, orders and response times every week.'};
test('business-fit approval queues an email but never activates the business',async()=>{reset();await decideBusinessFit('fixture','admin',input);assert.ok(f.writes.some(w=>w.values.includes('BUSINESS_FIT_APPROVED')&&w.sql.includes("'QUEUED'")));assert.equal(f.writes.some(w=>w.sql.includes('UPDATE procurement_partners')),false);assert.equal(f.writes[0].values[1],'SUBMITTED');});
test('clarification reopens the case; not-ready does not activate or reopen it',async()=>{for(const [decision,status,action] of [['REQUEST_CHANGES','DRAFT','BUSINESS_FIT_CHANGES'],['NOT_READY','SUBMITTED','BUSINESS_FIT_NOT_READY']]){reset();await decideBusinessFit('fixture','admin',{...input,decision});assert.equal(f.writes[0].values[1],status);assert.ok(f.writes.some(w=>w.values.includes(action)));}});
test('draft and stale business-fit decisions are rejected',async()=>{for(const change of [{status:'DRAFT'},{revision:3},{businessStatus:'ACTIVE'}]){reset();Object.assign(f.row,change);await assert.rejects(decideBusinessFit('fixture','admin',input),e=>e.status===409);assert.equal(f.writes.length,0);}});
test('final activation rejects incomplete verification, business fit, agreement and stale reviews',async()=>{
 for(const change of [{kycStatus:'SUBMITTED'},{country:'GH'},{currency:'USD'},{revision:3},{businessStatus:'ACTIVE'},{reviewCiphertext:encode({businessFit:{decision:'REQUEST_CHANGES'}})}]){reset();Object.assign(f.row,change);await assert.rejects(activatePartner('fixture','admin',agreement),e=>e.status===409);assert.equal(f.writes.some(w=>w.sql.includes("status = 'ACTIVE'")),false);}
 reset();await assert.rejects(activatePartner('fixture','admin',{...agreement,agreementReviewed:false}),e=>e.status===422);
});
test('membership conflicts and existing affiliate accounts still block activation',async()=>{for(const key of ['conflict','affiliate']){reset();f[key]=true;await assert.rejects(activatePartner('fixture','admin',agreement),e=>e.status===409);assert.equal(f.writes.some(w=>w.sql.includes("status = 'ACTIVE'")),false);}});
test('final approval activates the business and collection and queues its notification',async()=>{reset();await activatePartner('fixture','admin',agreement);assert.ok(f.writes.some(w=>w.sql.includes("status = 'ACTIVE'")&&w.sql.includes('liveCollectionEnabled = true')));assert.ok(f.writes.some(w=>w.sql.includes('published = false')));assert.ok(f.writes.some(w=>w.sql.includes("'BUSINESS_ACTIVATED'")&&w.sql.includes("'QUEUED'")));});

test('admin cannot activate before business accepts the current agreement',async()=>{reset();f.agreementReady=false;await assert.rejects(activatePartner('fixture','admin',agreement),e=>e.status===409);assert.equal(f.writes.length,0);});
