'use client';
import {useEffect,useState} from 'react';
import type {CountryPolicy} from '@/lib/partners/country-policy';
const fresh:CountryPolicy={code:'',name:'',status:'DRAFT',verificationProfile:'UK_STANDARD',allowIndividuals:true,allowCompanies:true,billingCurrency:'GBP',settlementCurrency:'GBP',monthlyFeeMinor:0,trialDays:14,minimumAge:18,addressEvidenceMonths:3,requireIdentityMeeting:true,requireOwnNamePayout:true,extraDocuments:[],revision:0};
export default function CountryPolicies(){
 const [countries,setCountries]=useState<CountryPolicy[]>([]),[draft,setDraft]=useState<CountryPolicy|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(false);
 async function load(){setBusy(true);try{const r=await fetch('/api/partners/countries',{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.message);setCountries(b.countries);}catch(e){setError(true);setNotice((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);
 const field='min-h-11 w-full rounded-lg border border-border bg-background px-3 py-2 text-foreground';
 return <div className="space-y-6">
 <div className="flex flex-wrap items-center justify-between gap-4"><p className="text-sm text-muted-foreground">Open applications country by country. Opening applications does not bypass verification or enable unsupported payments and payouts.</p><button className="rounded-lg border border-border bg-card px-4 py-2.5 text-sm font-medium" disabled={busy} onClick={()=>{setDraft({...fresh});setNotice('');}}>Add country</button></div>
 {notice?<p role={error?'alert':'status'} className={`rounded-lg border p-4 text-sm ${error?'border-red-500/30 bg-red-500/10 text-red-600 dark:text-red-300':'border-green-500/30 bg-green-500/10 text-green-700 dark:text-green-300'}`}>{notice}</p>:null}
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{countries.map(c=><button key={c.code} type="button" onClick={()=>{setDraft(c);setNotice('');}} className="rounded-xl border border-border bg-card p-5 text-left transition-colors hover:bg-muted"><div className="flex items-center justify-between gap-4"><h2 className="text-lg font-semibold">{c.name}</h2><span className="text-xs font-medium text-muted-foreground">{c.status}</span></div><p className="mt-3 text-sm text-muted-foreground">{c.billingCurrency} {(c.monthlyFeeMinor/100).toFixed(2)} / month · {c.trialDays}-day trial · {c.settlementCurrency} payouts</p><p className="mt-2 text-sm">{[c.allowIndividuals?'Individuals':'',c.allowCompanies?'Businesses':''].filter(Boolean).join(' and ')} · Revision {c.revision}</p></button>)}</div>
 {draft?<form className="space-y-6 rounded-xl border border-border bg-card p-5 sm:p-7" onSubmit={async e=>{e.preventDefault();setBusy(true);setNotice('');try{const r=await fetch('/api/partners/countries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)}),b=await r.json();if(!r.ok)throw Error(b.message);setDraft(b.country);setError(false);setNotice(b.message);await load();}catch(e){setError(true);setNotice((e as Error).message);}finally{setBusy(false);}}}>
 <h2 className="text-xl font-semibold">{draft.revision?'Edit country':'New country'}</h2>
 <div className="grid gap-5 sm:grid-cols-2">{([['code','Country code'],['name','Country name'],['billingCurrency','Platform billing currency'],['settlementCurrency','Earnings and withdrawal currency']] as const).map(([key,label])=><label className="space-y-2 text-sm font-medium" key={key}><span>{label}</span><input required className={field} value={draft[key]} disabled={busy||(key==='code'&&draft.revision>0)} maxLength={key==='code'?2:(key==='billingCurrency'||key==='settlementCurrency')?3:80} onChange={e=>setDraft({...draft,[key]:key==='name'?e.target.value:e.target.value.toUpperCase()})}/></label>)}
 <label className="space-y-2 text-sm font-medium"><span>Monthly fee ({draft.billingCurrency}, excluding processing fees)</span><input required type="number" min="0" max="1000000" step="0.01" className={field} value={draft.monthlyFeeMinor/100} onChange={e=>setDraft({...draft,monthlyFeeMinor:Math.round(Number(e.target.value)*100)})}/></label>
 {([['trialDays','Free trial (days)',0,365],['minimumAge','Minimum age',18,100],['addressEvidenceMonths','Address evidence maximum age (months)',1,6]] as const).map(([key,label,min,max])=><label className="space-y-2 text-sm font-medium" key={key}><span>{label}</span><input required type="number" min={min} max={max} className={field} value={draft[key]} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})}/></label>)}</div>
 <fieldset><legend className="mb-3 text-sm font-semibold">Application availability</legend><div className="flex flex-wrap gap-5">{(['DRAFT','OPEN','PAUSED'] as const).map(status=><label key={status} className="flex items-center gap-2 text-sm"><input type="radio" name="status" checked={draft.status===status} onChange={()=>setDraft({...draft,status})}/>{status==='OPEN'?'Applications open':status==='DRAFT'?'Draft':'Paused'}</label>)}</div></fieldset>
 <fieldset><legend className="mb-3 text-sm font-semibold">Verification profile</legend><div className="flex flex-wrap gap-5">{([['NG_BUSINESS','Nigerian registered business'],['UK_STANDARD','UK identity and business checks']] as const).map(([value,label])=><label key={value} className="flex items-center gap-2 text-sm"><input type="radio" name="profile" checked={draft.verificationProfile===value} onChange={()=>setDraft({...draft,verificationProfile:value})}/>{label}</label>)}</div></fieldset>
 <div className="grid gap-4 sm:grid-cols-2">{([['allowIndividuals','Accept individuals'],['allowCompanies','Accept registered businesses'],['requireIdentityMeeting','Require manual identity/video check'],['requireOwnNamePayout','Require verified own-name payout account']] as const).map(([key,label])=><label key={key} className="flex items-center gap-3 text-sm"><input type="checkbox" checked={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.checked})}/>{label}</label>)}</div>
 <fieldset className="space-y-4"><legend className="mb-2 text-sm font-semibold">Additional required documents</legend>{draft.extraDocuments.map((doc,i)=><div key={i} className="grid items-end gap-3 sm:grid-cols-[1fr_2fr_auto]"><label className="space-y-2 text-sm">Document key<input required className={field} value={doc.key} placeholder="PROFESSIONAL_CERTIFICATE" onChange={e=>setDraft({...draft,extraDocuments:draft.extraDocuments.map((d,j)=>i===j?{...d,key:e.target.value.toUpperCase()}:d)})}/></label><label className="space-y-2 text-sm">Instructions for applicant<input required className={field} value={doc.label} onChange={e=>setDraft({...draft,extraDocuments:draft.extraDocuments.map((d,j)=>i===j?{...d,label:e.target.value}:d)})}/></label><button type="button" className="min-h-11 rounded-lg border border-border px-4 text-sm" onClick={()=>setDraft({...draft,extraDocuments:draft.extraDocuments.filter((_,j)=>j!==i)})}>Remove</button></div>)}<button type="button" disabled={draft.extraDocuments.length>=10} className="rounded-lg border border-border px-4 py-2.5 text-sm" onClick={()=>setDraft({...draft,extraDocuments:[...draft.extraDocuments,{key:'',label:''}]})}>Add document requirement</button></fieldset>
 <p className="text-sm text-muted-foreground">Changes apply to new applications. Country currency and pricing are not a substitute for a supported billing, delivery or settlement integration. Existing subscriptions require explicit consent to changed prices.</p>
 <div className="flex flex-wrap gap-3"><button disabled={busy} className="rounded-lg bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">{busy?'Saving…':'Save country policy'}</button><button type="button" disabled={busy} className="rounded-lg border border-border px-5 py-3 text-sm" onClick={()=>setDraft(null)}>Close editor</button></div>
 </form>:null}</div>;
}
